mainAddr:
  host: "localhost"
  port: 8000
addressEntries:
  - frontendAddr:
      host: "localhost"
      port: 8001
    serverAddr:
      host: "localhost"
      port: 9001
  - frontendAddr:
      host: "localhost"
      port: 8002
    serverAddr:
      host: "localhost"
      port: 5000